"""Add foreign key relationships and indices

Revision ID: 1663633ecdcd
Revises: 
Create Date: 2025-06-16 19:03:11.822528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1663633ecdcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.create_index('idx_blog_user', ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('blog_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index('idx_comment_blog', ['blog_id'], unique=False)
        batch_op.create_index('idx_comment_parent', ['parent_id'], unique=False)
        batch_op.create_index('idx_comment_user', ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('comment_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment_like', schema=None) as batch_op:
        batch_op.create_index('idx_comment_like_blog', ['blog_id'], unique=False)
        batch_op.create_index('idx_comment_like_comment', ['comment_id'], unique=False)
        batch_op.create_index('idx_comment_like_user', ['user_id'], unique=False)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index('idx_like_blog', ['blog_id'], unique=False)
        batch_op.create_index('idx_like_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index('idx_like_user')
        batch_op.drop_index('idx_like_blog')

    with op.batch_alter_table('comment_like', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_like_user')
        batch_op.drop_index('idx_comment_like_comment')
        batch_op.drop_index('idx_comment_like_blog')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_parent_id_fkey'), 'comment', ['parent_id'], ['id'])
        batch_op.drop_index('idx_comment_user')
        batch_op.drop_index('idx_comment_parent')
        batch_op.drop_index('idx_comment_blog')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_index('idx_blog_user')

    # ### end Alembic commands ###
